<?php
require __DIR__ . '/includes/bootstrap.php';
require_login();
$pageTitle = 'Main Inventory';
$retail = ['items' => db_value($pdo, 'SELECT COUNT(*) FROM retail_inventory'), 'units' => db_value($pdo, 'SELECT COALESCE(SUM(quantity),0) FROM retail_inventory'), 'value' => db_value($pdo, 'SELECT COALESCE(SUM(quantity*price),0) FROM retail_inventory'), 'low' => db_value($pdo, 'SELECT COUNT(*) FROM retail_inventory WHERE quantity <= 3')];
$consignmentMain = ['items' => db_value($pdo, 'SELECT COUNT(*) FROM consignment_main_inventory'), 'units' => db_value($pdo, 'SELECT COALESCE(SUM(total_stock),0) FROM consignment_main_inventory'), 'value' => db_value($pdo, 'SELECT COALESCE(SUM(total_stock*sale_price),0) FROM consignment_main_inventory'), 'low' => db_value($pdo, 'SELECT COUNT(*) FROM consignment_main_inventory WHERE total_stock <= 3')];
$consignorStock = ['items' => db_value($pdo, 'SELECT COUNT(*) FROM consignment_inventory'), 'units' => db_value($pdo, 'SELECT COALESCE(SUM(stock_balance),0) FROM consignment_inventory')];
require __DIR__ . '/includes/header.php';
?>
<div class="grid gap-6 lg:grid-cols-2">
    <div class="pvn-card p-6"><h3 class="text-xl font-semibold mb-4">Retail Inventory</h3><div class="grid grid-cols-2 gap-4"><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Items</div><div class="text-3xl font-semibold"><?= e((string)$retail['items']) ?></div></div><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Units</div><div class="text-3xl font-semibold"><?= e((string)$retail['units']) ?></div></div><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Stock Value</div><div class="text-3xl font-semibold"><?= e(money($retail['value'])) ?></div></div><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Low Stock</div><div class="text-3xl font-semibold"><?= e((string)$retail['low']) ?></div></div></div><a href="retail_inventory.php" class="inline-flex mt-5 rounded-2xl border px-4 py-2">Open Retail Inventory</a></div>
    <div class="pvn-card p-6"><h3 class="text-xl font-semibold mb-4">Consignment Main Inventory</h3><div class="grid grid-cols-2 gap-4"><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Main Items</div><div class="text-3xl font-semibold"><?= e((string)$consignmentMain['items']) ?></div></div><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Main Units</div><div class="text-3xl font-semibold"><?= e((string)$consignmentMain['units']) ?></div></div><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Main Stock Value</div><div class="text-3xl font-semibold"><?= e(money($consignmentMain['value'])) ?></div></div><div class="rounded-2xl bg-neutral-50 p-4"><div class="text-sm text-neutral-500">Consignor On Hand</div><div class="text-3xl font-semibold"><?= e((string)$consignorStock['units']) ?></div></div></div><div class="mt-5 flex gap-3"><a href="consignment_main_inventory.php" class="inline-flex rounded-2xl border px-4 py-2">Main Inventory</a><a href="consignment_inventory.php" class="inline-flex rounded-2xl border px-4 py-2">Consignor Stock</a></div></div>
</div>
<?php require __DIR__ . '/includes/footer.php'; ?>
